### ISSUE TITLE
All levels of the Table of Contents should be collapsible

### ISSUE THREAD

**Issue by LeazeDev** [voidblaster/AMP#3]
In the Table of Contents, all levels of the hierarchy should be collapsible (even groups.
Otherwise, if you have a lot of Groups, the ToC gets very overloaded very fast.
(maybe also collapse everything by default)

**Comment by 0xEAB** [comment]
Is this something that has to be fixed in AMP or is it a problem of the [factory template](https://github.com/MarkusLei22/AMP-Template/issues)?

**Comment by LMKight** [comment]
Made groups in the toc collapsable (in the AMP-Template repository)
